-- MySQL Script generated by MySQL Workbench
-- Wed Apr 30 12:26:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema POS_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema POS_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `POS_DB` DEFAULT CHARACTER SET utf8 ;
USE `POS_DB` ;

-- -----------------------------------------------------
-- Table `POS_DB`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Admin` (
  `Admin_Id` INT NOT NULL AUTO_INCREMENT,
  `Admin_Username` VARCHAR(50) NULL,
  `Admin_Password` CHAR(18) NULL,
  PRIMARY KEY (`Admin_Id`),
  UNIQUE INDEX `Admin_Id_UNIQUE` (`Admin_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`Cashier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Cashier` (
  `Cashier_Id` INT NOT NULL AUTO_INCREMENT,
  `Cashier_Username` VARCHAR(50) NULL,
  `Cashier_Password` CHAR(18) NULL,
  PRIMARY KEY (`Cashier_Id`),
  UNIQUE INDEX `Cashier_Id_UNIQUE` (`Cashier_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Product` (
  `Product_Id` INT NOT NULL AUTO_INCREMENT,
  `ItemName` VARCHAR(150) NULL,
  `Category` VARCHAR(100) NULL,
  `Sku` VARCHAR(50) NULL,
  `Product_Quantity` INT NULL,
  `UnitPrice` DECIMAL(10,2) NULL,
  `Supplier` VARCHAR(50) NULL,
  `RestockLevel` INT NULL,
  `AddedAt` DATETIME NULL,
  `ExpirationDate` DATE NULL,
  PRIMARY KEY (`Product_Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Product_Id` ASC) VISIBLE,
  INDEX `idx_product_Product_ItemName` (`ItemName` ASC) INVISIBLE,
  INDEX `idx_product_Product_Category` (`Category` ASC) VISIBLE)
ENGINE = InnoDB
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `POS_DB`.`AddCashierMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`AddCashierMember` (
  `AddCashierMember_Id` INT NOT NULL AUTO_INCREMENT,
  `PinCode` CHAR(4) NULL,
  `FullName` VARCHAR(50) NULL,
  `CreatedAt` DATETIME NULL,
  `Cashier_Id` INT NOT NULL,
  UNIQUE INDEX `Id_UNIQUE` (`AddCashierMember_Id` ASC) VISIBLE,
  PRIMARY KEY (`AddCashierMember_Id`, `Cashier_Id`),
  INDEX `idx_addcashiermember_AddCashierMember_FullName` (`FullName` ASC) VISIBLE,
  INDEX `Cashier_Id_idx` (`Cashier_Id` ASC) VISIBLE,
  UNIQUE INDEX `Cashier_Id_UNIQUE` (`Cashier_Id` ASC) VISIBLE,
  CONSTRAINT `Cashier_Id`
    FOREIGN KEY (`Cashier_Id`)
    REFERENCES `POS_DB`.`Cashier` (`Cashier_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`OrderHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`OrderHistory` (
  `OrderHistory_Id` INT NOT NULL AUTO_INCREMENT,
  `OrderType` ENUM('Dine In', 'Take Out') NULL,
  `OrderHistory_TotalAmount` DECIMAL(10,2) NULL,
  `OrderHistory_PaymentMethod` ENUM('Cash', 'GCash', 'Card') NULL,
  `OrderDate` DATE NULL,
  `AddCashierMember_Id` INT NOT NULL,
  UNIQUE INDEX `Id_UNIQUE` (`OrderHistory_Id` ASC) VISIBLE,
  PRIMARY KEY (`OrderHistory_Id`, `AddCashierMember_Id`),
  INDEX `AddCashierMember_Id_idx` (`AddCashierMember_Id` ASC) VISIBLE,
  UNIQUE INDEX `AddCashierMember_Id_UNIQUE` (`AddCashierMember_Id` ASC) VISIBLE,
  CONSTRAINT `AddCashierMember_Id`
    FOREIGN KEY (`AddCashierMember_Id`)
    REFERENCES `POS_DB`.`AddCashierMember` (`AddCashierMember_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`Receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Receipt` (
  `Receipt_Id` INT NOT NULL AUTO_INCREMENT,
  `TransactionRefNo` VARCHAR(50) NULL,
  `Receipt_TotalAmount` DECIMAL(10,2) NULL,
  `Receipt_PaymentMethod` ENUM('Cash', 'GCash', 'Card') NULL,
  `Receipt_CreatedAt` DATETIME NULL,
  `Order_Id` INT NOT NULL,
  PRIMARY KEY (`Receipt_Id`, `Order_Id`),
  UNIQUE INDEX `Order_Id_UNIQUE` (`Order_Id` ASC) VISIBLE,
  UNIQUE INDEX `Receipt_Id_UNIQUE` (`Receipt_Id` ASC) VISIBLE,
  CONSTRAINT `Order_Id`
    FOREIGN KEY (`Order_Id`)
    REFERENCES `POS_DB`.`OrderHistory` (`OrderHistory_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Menu` (
  `Menu_Id` INT NOT NULL AUTO_INCREMENT,
  `Price` DECIMAL(10,2) NULL,
  `Product_Id` INT NOT NULL,
  PRIMARY KEY (`Menu_Id`, `Product_Id`),
  UNIQUE INDEX `Menu_Id_UNIQUE` (`Menu_Id` ASC) VISIBLE,
  INDEX `Product_Id_idx` (`Product_Id` ASC) VISIBLE,
  UNIQUE INDEX `Product_Id_UNIQUE` (`Product_Id` ASC) VISIBLE,
  CONSTRAINT `Product_Id`
    FOREIGN KEY (`Product_Id`)
    REFERENCES `POS_DB`.`Product` (`Product_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`OrderDetails` (
  `OrderDetails_Id` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NULL,
  `SubTotal` DECIMAL NULL,
  `Menu_Id` INT NOT NULL,
  `OrderHistory_Id` INT NOT NULL,
  PRIMARY KEY (`OrderDetails_Id`, `OrderHistory_Id`, `Menu_Id`),
  UNIQUE INDEX `Order_Id_UNIQUE` (`OrderDetails_Id` ASC) VISIBLE,
  INDEX `OrderHistory_Id_idx` (`OrderHistory_Id` ASC) VISIBLE,
  INDEX `Menu_Id_idx` (`Menu_Id` ASC) VISIBLE,
  UNIQUE INDEX `Menu_Id_UNIQUE` (`Menu_Id` ASC) VISIBLE,
  UNIQUE INDEX `OrderHistory_Id_UNIQUE` (`OrderHistory_Id` ASC) VISIBLE,
  CONSTRAINT `OrderHistory_Id`
    FOREIGN KEY (`OrderHistory_Id`)
    REFERENCES `POS_DB`.`OrderHistory` (`OrderHistory_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Menu_Id`
    FOREIGN KEY (`Menu_Id`)
    REFERENCES `POS_DB`.`Menu` (`Menu_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `POS_DB` ;

-- -----------------------------------------------------
-- procedure routine1
-- -----------------------------------------------------

DELIMITER $$
USE `POS_DB`$$
CREATE PROCEDURE `routine1` ()
BEGIN

/*
-- Query: 
-- Date: 2025-04-30 12:07
*/
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (1,'Macaroni Pasta','Main Dish','0',0,112.64,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (2,'Pork BBQ with Java Rice','Main Dish','0',0,568.2,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (3,'Pancit Canton','Main Dish','0',0,139.9,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (4,'Kamote Fries with Ketchup','Appetizer','0',0,50,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (5,'Adobong Kangkong with Tofu and Rice','Main Dish','0',0,98.26,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (6,'Pork and Beans with Wheat Bread','Appetizer','0',0,457.64,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (7,'Spaghetti Pasta','Main Dish','0',0,41.98,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (8,'Veggie Pancit Canton','Main Dish','0',0,85.11,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (9,'Shredded Chicken Bistek with Brown Rice','Main Dish','0',0,183.93,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (10,'Ube Champorado with Oatmeal','Main Dish','0',0,500.87,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (11,'Shanghai with Garlic Brown Rice','Main Dish','0',0,269.16,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (12,'Tapa with Egg and Brown Rice','Main Dish','0',0,364.11,'Supplier Name',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (13,'Bento I','Main Dish','0',0,100,'23rd Cafe',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (14,'Bento II','Main Dish','0',0,100,'23rd Cafe',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (15,'Bento III','Main Dish','0',0,100,'23rd Cafe',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (16,'Bento IV','Main Dish','0',0,100,'23rd Cafe',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (17,'Coookies','Dessert','0',0,50,'23rd Cafe',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (18,'Brownies','Dessert','0',0,45,'23rd Cafe',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (19,'Tarts','Dessert','0',0,45,'23rd Cafe',0,'2025-04-30 11:29:30','2025-05-01');
INSERT INTO `Product` (`Product_Id`,`ItemName`,`Category`,`Sku`,`Product_Quantity`,`UnitPrice`,`Supplier`,`RestockLevel`,`AddedAt`,`ExpirationDate`) VALUES (20,'Chocolate Muffin','Dessert','0',0,95,'23rd Cafe',0,'2025-04-30 11:29:30','2025-05-01');


END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure routine2
-- -----------------------------------------------------

DELIMITER $$
USE `POS_DB`$$
CREATE PROCEDURE `routine2` ()
BEGIN

/*
-- Query: 
-- Date: 2025-04-30 12:07
*/
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (1,112.64,1);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (2,568.2,2);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (3,139.9,3);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (4,50,4);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (5,98.26,5);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (6,457.64,6);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (7,41.98,7);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (8,85.11,8);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (9,183.93,9);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (10,500.87,10);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (11,269.16,11);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (12,364.11,12);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (13,100,13);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (14,100,14);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (15,100,15);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (16,100,16);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (17,50,17);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (18,45,18);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (19,45,19);
INSERT INTO `Menu` (`Menu_Id`,`Price`,`Product_Id`) VALUES (20,95,20);


END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
