-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 18:21:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema POS_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema POS_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `POS_DB` DEFAULT CHARACTER SET utf8 ;
USE `POS_DB` ;

-- -----------------------------------------------------
-- Table `POS_DB`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Admin` (
  `Admin_Id` INT NOT NULL AUTO_INCREMENT,
  `Admin_Username` VARCHAR(50) NOT NULL,
  `Admin_Password` CHAR(18) NOT NULL,
  PRIMARY KEY (`Admin_Id`),
  UNIQUE INDEX `Admin_Id_UNIQUE` (`Admin_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`Cashier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Cashier` (
  `Cashier_Id` INT NOT NULL AUTO_INCREMENT,
  `Cashier_Username` VARCHAR(50) NOT NULL,
  `Cashier_Password` CHAR(18) NOT NULL,
  PRIMARY KEY (`Cashier_Id`),
  UNIQUE INDEX `Cashier_Id_UNIQUE` (`Cashier_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Product` (
  `Product_Id` INT NOT NULL AUTO_INCREMENT,
  `ItemName` VARCHAR(150) NOT NULL,
  `Category` VARCHAR(100) NOT NULL,
  `Sku` VARCHAR(50) NOT NULL,
  `Product_Quantity` INT NOT NULL,
  `UnitPrice` DECIMAL(10,2) NOT NULL,
  `Supplier` VARCHAR(50) NOT NULL,
  `RestockLevel` INT NOT NULL,
  `AddedAt` DATETIME NOT NULL,
  `ExpirationDate` DATE NOT NULL,
  PRIMARY KEY (`Product_Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Product_Id` ASC) VISIBLE,
  INDEX `idx_product_Product_ItemName` (`ItemName` ASC) INVISIBLE,
  INDEX `idx_product_Product_Category` (`Category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`AddCashierMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`AddCashierMember` (
  `AddCashierMember_Id` INT NOT NULL AUTO_INCREMENT,
  `PinCode` CHAR(4) NOT NULL,
  `FullName` VARCHAR(50) NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `Cashier_Id` INT NOT NULL,
  UNIQUE INDEX `Id_UNIQUE` (`AddCashierMember_Id` ASC) VISIBLE,
  PRIMARY KEY (`AddCashierMember_Id`, `Cashier_Id`),
  INDEX `idx_addcashiermember_AddCashierMember_FullName` (`FullName` ASC) VISIBLE,
  INDEX `Cashier_Id_idx` (`Cashier_Id` ASC) VISIBLE,
  CONSTRAINT `Cashier_Id`
    FOREIGN KEY (`Cashier_Id`)
    REFERENCES `POS_DB`.`Cashier` (`Cashier_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`OrderHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`OrderHistory` (
  `OrderHistory_Id` INT NOT NULL AUTO_INCREMENT,
  `OrderType` ENUM('Dine In', 'Take Out') NOT NULL,
  `OrderHistory_TotalAmount` DECIMAL(10,2) NOT NULL,
  `OrderHistory_PaymentMethod` ENUM('Cash', 'GCash', 'Card') NOT NULL,
  `OrderDate` DATE NOT NULL,
  `AddCashierMember_Id` INT NOT NULL,
  UNIQUE INDEX `Id_UNIQUE` (`OrderHistory_Id` ASC) VISIBLE,
  PRIMARY KEY (`OrderHistory_Id`, `AddCashierMember_Id`),
  INDEX `AddCashierMember_Id_idx` (`AddCashierMember_Id` ASC) VISIBLE,
  CONSTRAINT `AddCashierMember_Id`
    FOREIGN KEY (`AddCashierMember_Id`)
    REFERENCES `POS_DB`.`AddCashierMember` (`AddCashierMember_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`Receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Receipt` (
  `Receipt_Id` INT NOT NULL AUTO_INCREMENT,
  `TransactionRefNo` VARCHAR(50) NOT NULL,
  `Receipt_TotalAmount` DECIMAL(10,2) NOT NULL,
  `Receipt_PaymentMethod` ENUM('Cash', 'GCash', 'Card') NOT NULL,
  `Receipt_CreatedAt` DATETIME NOT NULL,
  `Order_Id` INT NOT NULL,
  PRIMARY KEY (`Receipt_Id`, `Order_Id`),
  UNIQUE INDEX `Order_Id_UNIQUE` (`Order_Id` ASC) VISIBLE,
  UNIQUE INDEX `Receipt_Id_UNIQUE` (`Receipt_Id` ASC) VISIBLE,
  CONSTRAINT `Order_Id`
    FOREIGN KEY (`Order_Id`)
    REFERENCES `POS_DB`.`OrderHistory` (`OrderHistory_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`Menu` (
  `Menu_Id` INT NOT NULL AUTO_INCREMENT,
  `Price` DECIMAL(10,2) NOT NULL,
  `Product_Id` INT NOT NULL,
  PRIMARY KEY (`Menu_Id`, `Product_Id`),
  UNIQUE INDEX `Menu_Id_UNIQUE` (`Menu_Id` ASC) VISIBLE,
  INDEX `Product_Id_idx` (`Product_Id` ASC) VISIBLE,
  CONSTRAINT `Product_Id`
    FOREIGN KEY (`Product_Id`)
    REFERENCES `POS_DB`.`Product` (`Product_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_DB`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_DB`.`OrderDetails` (
  `OrderDetails_Id` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NOT NULL,
  `SubTotal` DECIMAL NOT NULL,
  `Menu_Id` INT NOT NULL,
  `OrderHistory_Id` INT NOT NULL,
  PRIMARY KEY (`OrderDetails_Id`, `OrderHistory_Id`, `Menu_Id`),
  UNIQUE INDEX `Order_Id_UNIQUE` (`OrderDetails_Id` ASC) VISIBLE,
  INDEX `OrderHistory_Id_idx` (`OrderHistory_Id` ASC) VISIBLE,
  INDEX `Menu_Id_idx` (`Menu_Id` ASC) VISIBLE,
  CONSTRAINT `OrderHistory_Id`
    FOREIGN KEY (`OrderHistory_Id`)
    REFERENCES `POS_DB`.`OrderHistory` (`OrderHistory_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Menu_Id`
    FOREIGN KEY (`Menu_Id`)
    REFERENCES `POS_DB`.`Menu` (`Menu_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
