-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 16:14:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pos_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pos_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pos_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `Admin_Username` VARCHAR(50) NOT NULL,
  `Admin_Password` CHAR(18) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cashier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cashier` (
  `Cashier_Username` VARCHAR(50) NOT NULL,
  `Cashier_Password` CHAR(18) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `Product_Id` INT NOT NULL AUTO_INCREMENT,
  `Product_ItemName` VARCHAR(150) NOT NULL,
  `Product_Category` VARCHAR(100) NOT NULL,
  `Product_Sku` VARCHAR(50) NOT NULL,
  `Product_Quantity` INT NOT NULL,
  `Product_UnitPrice` DECIMAL(10,2) NOT NULL,
  `Product_Supplier` VARCHAR(50) NOT NULL,
  `Product_RestockLevel` INT NOT NULL,
  `Product_AddedAt` DATETIME NOT NULL,
  `Product_ExpirationDate` DATE NOT NULL,
  PRIMARY KEY (`Product_Id`, `Product_ItemName`, `Product_Category`),
  UNIQUE INDEX `Id_UNIQUE` (`Product_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AddCashierMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AddCashierMember` (
  `AddCashierMember_Id` INT NOT NULL AUTO_INCREMENT,
  `AddCashierMember_PinCode` CHAR(4) NOT NULL,
  `AddCashierMember_FullName` VARCHAR(50) NOT NULL,
  `AddCashierMember_CreatedAt` DATETIME NOT NULL,
  UNIQUE INDEX `Id_UNIQUE` (`AddCashierMember_Id` ASC) VISIBLE,
  PRIMARY KEY (`AddCashierMember_Id`, `AddCashierMember_PinCode`, `AddCashierMember_FullName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderHistory` (
  `OrderHistory_Id` INT NOT NULL AUTO_INCREMENT,
  `OrderHistory_OrderType` ENUM('Dine In', 'Take Out') NOT NULL,
  `OrderHistory_TotalAmount` DECIMAL(10,2) NOT NULL,
  `OrderHistory_PaymentMethod` ENUM('Cash', 'GCash', 'Card') NOT NULL,
  `OrderDate` DATE NOT NULL,
  `OderHistory_MobileNumber` INT NOT NULL,
  `AddCashierMember_FullName` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `Id_UNIQUE` (`OrderHistory_Id` ASC) VISIBLE,
  INDEX `AddCashierMemberFullName_idx` (`AddCashierMember_FullName` ASC) VISIBLE,
  PRIMARY KEY (`OrderHistory_Id`),
  CONSTRAINT `AddCashierMemberFullName`
    FOREIGN KEY (`AddCashierMember_FullName`)
    REFERENCES `mydb`.`AddCashierMember` (`AddCashierMember_FullName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Receipt` (
  `Receipt_Id` INT NOT NULL,
  `Receipt_TransactionRefNo` VARCHAR(50) NULL,
  `Receipt_TotalAmount` DECIMAL(10,2) NOT NULL,
  `Receipt_PaymentMethod` ENUM('Cash', 'GCash', 'Card') NOT NULL,
  `Receipt_CreatedAt` DATETIME NOT NULL,
  `Order_Id` INT NOT NULL,
  PRIMARY KEY (`Receipt_Id`),
  UNIQUE INDEX `Order_Id_UNIQUE` (`Order_Id` ASC) VISIBLE,
  CONSTRAINT `Order_Id`
    FOREIGN KEY (`Order_Id`)
    REFERENCES `mydb`.`OrderHistory` (`OrderHistory_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `Menu_Id` INT NOT NULL AUTO_INCREMENT,
  `Menu_Price` DECIMAL(10,2) NOT NULL,
  `Product_ItemName` VARCHAR(150) NOT NULL,
  `Product_Category` VARCHAR(100) NOT NULL,
  INDEX `ProductItemName_idx` (`Product_ItemName` ASC) VISIBLE,
  INDEX `ProductCategory_idx` (`Product_Category` ASC) VISIBLE,
  PRIMARY KEY (`Menu_Id`),
  UNIQUE INDEX `Menu_Id_UNIQUE` (`Menu_Id` ASC) VISIBLE,
  CONSTRAINT `ProductItemName`
    FOREIGN KEY (`Product_ItemName`)
    REFERENCES `mydb`.`Product` (`Product_ItemName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProductCategory`
    FOREIGN KEY (`Product_Category`)
    REFERENCES `mydb`.`Product` (`Product_Category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pos_system` ;

-- -----------------------------------------------------
-- Table `pos_system`.`addcashiermember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos_system`.`addcashiermember` (
  `AddCashierMember_Id` INT NOT NULL AUTO_INCREMENT,
  `AddCashierMember_PinCode` CHAR(4) NOT NULL,
  `AddCashierMember_FullName` VARCHAR(50) NOT NULL,
  `AddCashierMember_CreatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`AddCashierMember_Id`, `AddCashierMember_PinCode`, `AddCashierMember_FullName`),
  UNIQUE INDEX `AddCashierMember_Id` (`AddCashierMember_Id` ASC) VISIBLE,
  INDEX `idx_addcashiermember_AddCashierMember_FullName` (`AddCashierMember_FullName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pos_system`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos_system`.`admin` (
  `Admin_Username` VARCHAR(50) NOT NULL,
  `Admin_Password` CHAR(18) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pos_system`.`cashier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos_system`.`cashier` (
  `Cashier_Username` VARCHAR(50) NOT NULL,
  `Cashier_Password` CHAR(18) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pos_system`.`orderhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos_system`.`orderhistory` (
  `OrderHistory_Id` INT NOT NULL AUTO_INCREMENT,
  `OrderHistory_OrderType` ENUM('Dine In', 'Take Out') NOT NULL,
  `OrderHistory_TotalAmount` DECIMAL(10,2) NOT NULL,
  `OrderHistory_PaymentMethod` ENUM('Cash', 'GCash', 'Card') NOT NULL,
  `OderHistory_MobileNumber` INT NOT NULL,
  `AddCashierMember_FullName` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`OrderHistory_Id`),
  UNIQUE INDEX `OrderHistory_Id` (`OrderHistory_Id` ASC) VISIBLE,
  INDEX `AddCashierMember_FullName` (`AddCashierMember_FullName` ASC) VISIBLE,
  CONSTRAINT `orderhistory_ibfk_1`
    FOREIGN KEY (`AddCashierMember_FullName`)
    REFERENCES `pos_system`.`addcashiermember` (`AddCashierMember_FullName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
